name: Build and Package
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-26.04
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          check-latest: true
          package-manager-cache: false
      - name: Set up PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 9
          cache: false
          run_install: true
      - name: Set up Rust
        run: rustup update
      - name: Build frontend
        id: metadata
        run: |
          pnpm build
          project_name=$(jq -r '.name' plugin.json)
          project_version=$(jq -r '.version' package.json)
          echo "project_name=$project_name" >> $GITHUB_OUTPUT
          echo "project_version=$project_version" >> $GITHUB_OUTPUT
          mkdir -p "$project_name/bin"
          cp -r dist "$project_name"
      - name: Build backend
        run: |
          binary_name=$(awk -F ' = ' '$1 == "name" {print $2}' backend/Cargo.toml | tr -d '\"')
          cargo build --release --manifest-path backend/Cargo.toml
          chmod +x backend/target/release/$binary_name
          cp backend/target/release/$binary_name "${{ steps.metadata.outputs.project_name }}/bin/backend"
          cp main.py "${{ steps.metadata.outputs.project_name }}"
          cp LICENSE "${{ steps.metadata.outputs.project_name }}"
          cp README.md "${{ steps.metadata.outputs.project_name }}"
          cp package.json "${{ steps.metadata.outputs.project_name }}"
          cp plugin.json "${{ steps.metadata.outputs.project_name }}"
          mkdir -p build
          cp -r "${{ steps.metadata.outputs.project_name }}" build
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ steps.metadata.outputs.project_name }}-${{ steps.metadata.outputs.project_version }}"
          path: "build"
          if-no-files-found: error
