name: Decky CLI Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Decky CLI Build
        run: |
          mkdir $(pwd)/cli
          curl -L -o $(pwd)/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x $(pwd)/cli/decky
          $(pwd)/cli/decky plugin build $(pwd)

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "decky-wine-cellar"
          path: "out"